version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - ENV=production
    
  monitoring:
    image: python:3.9-slim
    command: python monitoring/drift_detection.py
    volumes:
      - .:/app
    depends_on:
      - api