scripts:
  A:
    base_conversion: 0.25
    time_impact:
      9: -0.1
      14: 0.2
    target_regions: [North, East]
    
  B:
    base_conversion: 0.35
    time_impact:
      10: 0.1
      15: 0.3
    target_regions: [South, West]
    
  C:
    base_conversion: 0.15
    time_impact:
      16: 0.4
    target_regions: [East]