name: ML Pipeline

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Exécution hebdomadaire

jobs:
  train-model:
    runs-on: ubuntu-latest
    container:
      image: your-docker-image
      credentials:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Data Update
        run: |
          python scripts/data_generator.py \
            --start-date $(date -d "last week" +%Y-%m-%d) \
            --days 7 \
            --output-dir data/raw
      
      - name: Retrain Model
        run: |
          python scripts/train_model.py \
            --input-dir data/raw \
            --model-dir models \
            --test-size 0.2
            
      - name: Deploy Model
        if: success()
        run: |
          aws s3 sync models/ s3://your-bucket/models/ \
            --exclude "*" \
            --include "production_model*"
            
      - name: Alert on Slack
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_COLOR: ${{ job.status }} 
          SLACK_ICON: https://github.com/fluidicon.png
          SLACK_MESSAGE: "Nouveau modèle déployé : ${{ github.sha }}"